package com.example.utils

import android.content.Context
import android.content.Intent
import android.widget.Toast
import androidx.core.content.FileProvider
import java.io.File

object ShareManager {

    suspend fun generateQuotationPdf(
        context: Context,
        repository: com.example.data.QuotesRepository,
        quotationId: Int
    ): File {
        val quotation = repository.getQuotationByIdDirect(quotationId)
            ?: throw IllegalArgumentException("Quotation not found with id: $quotationId")
        
        val cleanQuoteNum = quotation.quotationNumber.replace("/", "_")
        
        // Clean any potential old files with a similar prefix in cache to keep it clean
        val cacheDirFile = context.cacheDir
        try {
            cacheDirFile.listFiles()?.forEach { f ->
                if (f.name.startsWith("Quotation_${cleanQuoteNum}") && f.name.endsWith(".pdf")) {
                    f.delete()
                }
            }
        } catch (e: Exception) {
            e.printStackTrace()
        }

        // Generate a uniquely-named file to completely bypass external PDF viewer cache
        val timestamp = System.currentTimeMillis()
        val file = File(context.cacheDir, "Quotation_${cleanQuoteNum}_$timestamp.pdf")
        
        // Generate the PDF
        com.example.pdf.PdfGenerator.generateQuotationPdf(context, repository, quotationId, file)
        return file
    }

    fun shareQuotation(context: Context, file: File, quoteNumber: String) {
        try {
            val uri = FileProvider.getUriForFile(
                context,
                "com.aistudio.interiorproquotes.qyhtsn.provider",
                file
            )
            val intent = Intent(Intent.ACTION_SEND).apply {
                type = "application/pdf"
                putExtra(Intent.EXTRA_STREAM, uri)
                putExtra(Intent.EXTRA_SUBJECT, "Quotation $quoteNumber")
                putExtra(
                    Intent.EXTRA_TEXT,
                    "Dear Client,\nPlease find attached our quotation $quoteNumber for your review.\n\nGenerated by InteriorPro Quotes."
                )
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }
            context.startActivity(Intent.createChooser(intent, "Share Quotation PDF"))
        } catch (e: Exception) {
            Toast.makeText(context, "Error sharing PDF: ${e.message}", Toast.LENGTH_SHORT).show()
        }
    }

    fun shareToWhatsApp(context: Context, file: File, phoneNumber: String): Boolean {
        val whatsappPkg = getWhatsAppPackage(context)
        if (whatsappPkg == null) {
            Toast.makeText(context, "WhatsApp is not installed on this device.", Toast.LENGTH_LONG).show()
            return false
        }

        val cleanPhone = cleanPhoneNumber(phoneNumber)
        if (cleanPhone.isEmpty()) {
            Toast.makeText(context, "Invalid customer phone number.", Toast.LENGTH_SHORT).show()
            return false
        }

        try {
            val uri = FileProvider.getUriForFile(
                context,
                "com.aistudio.interiorproquotes.qyhtsn.provider",
                file
            )
            val intent = Intent(Intent.ACTION_SEND).apply {
                type = "application/pdf"
                putExtra(Intent.EXTRA_STREAM, uri)
                putExtra("jid", "$cleanPhone@s.whatsapp.net")
                setPackage(whatsappPkg)
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }
            context.startActivity(intent)
            return true
        } catch (e: Exception) {
            Toast.makeText(context, "Error sending to WhatsApp: ${e.message}", Toast.LENGTH_SHORT).show()
            return false
        }
    }

    fun openOrViewPdf(context: Context, file: File) {
        if (!isPdfViewerAvailable(context)) {
            Toast.makeText(
                context,
                "No PDF application is installed on this device. You can still share or save the quotation PDF.",
                Toast.LENGTH_LONG
            ).show()
            return
        }
        try {
            val uri = FileProvider.getUriForFile(
                context,
                "com.aistudio.interiorproquotes.qyhtsn.provider",
                file
            )
            val intent = Intent(Intent.ACTION_VIEW).apply {
                setDataAndType(uri, "application/pdf")
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }
            context.startActivity(Intent.createChooser(intent, "Open Quotation"))
        } catch (e: Exception) {
            Toast.makeText(context, "Error opening PDF: ${e.message}", Toast.LENGTH_SHORT).show()
        }
    }

    private fun isPdfViewerAvailable(context: Context): Boolean {
        val intent = Intent(Intent.ACTION_VIEW).apply {
            type = "application/pdf"
        }
        return try {
            val list = context.packageManager.queryIntentActivities(
                intent,
                android.content.pm.PackageManager.MATCH_DEFAULT_ONLY
            )
            list.isNotEmpty()
        } catch (e: Exception) {
            false
        }
    }

    private fun getWhatsAppPackage(context: Context): String? {
        val pm = context.packageManager
        val packages = listOf("com.whatsapp", "com.whatsapp.w4b")
        for (pkg in packages) {
            try {
                pm.getPackageInfo(pkg, 0)
                return pkg
            } catch (e: Exception) {
                // Package not found
            }
        }
        return null
    }

    private fun cleanPhoneNumber(phone: String): String {
        val digits = phone.filter { it.isDigit() }
        return if (digits.length == 10) {
            "91$digits"
        } else {
            digits
        }
    }
}
