package com.example.core.sync.validation

enum class ValidationError {
    MISSING_MANIFEST,
    MISSING_METADATA,
    MISSING_DATABASE,
    MISSING_ASSETS,
    MISSING_LOGO,
    MISSING_SIGNATURE,
    MISSING_COMPANY_SEAL,
    MISSING_THEME,
    MISSING_SETTINGS,
    INVALID_FORMAT,
    UNSUPPORTED_VERSION,
    INCOMPATIBLE_APP_VERSION,
    INCOMPATIBLE_DATABASE_VERSION,
    CHECKSUM_MISMATCH,
    ENCRYPTION_ERROR,
    // Future expansion
    INVALID_DIGITAL_SIGNATURE,
    INVALID_CERTIFICATE,
    UNTRUSTED_PACKAGE,
    INVALID_ENTERPRISE_LICENSE
}
